name: Alert validation repository
on: 
  release:
  push:
    branches:
      - main

jobs:
  build:
    name: Dispatch to `test-pybamm`
    runs-on: ubuntu-latest
    steps:
        - uses: mvasigh/dispatch-action@main
          with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            repo: test-pybamm
            owner: Vaibhav-Chopra-GT
            event_type: ${{ github.event_name }}
            message: |
              {
                "commit_hash": "$GITHUB_SHA"
              }
